name: python
on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: versions
        run: |
          sw_vers
          xcodebuild -version
          which python
          python -V
      - name: install task
        run: |
          brew install pipenv
          sudo easy_install pip
          which pip
          pip -V
          sudo pip install mock --upgrade --ignore-installed six
          sudo pip install pyobjc
      - name: run test
        run: python -m unittest discover --start-directory ./tests/scripts
