name: python
on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: which python
      - run: brew install pipenv
      - run: sudo easy_install pip
      - run: sudo /usr/bin/python -m pip install mock --upgrade --ignore-installed six
      - run: pipenv run test
