name: python
on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: brew install pipenv
      - run: sudo easy_install pip
      - run: pipenv run test_install
      - run: pipenv run test
