name: python
on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: which python
      - run: python -V
      - run: brew install pipenv
      - run: sudo easy_install pip
      - run: which pip
      - run: pip -V
      - run: sudo pip install mock --upgrade --ignore-installed six
      - run: python -m unittest discover --start-directory ./tests/scripts
