name: python
on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: versions
        run: |
          sw_vers
          xcodebuild -version
          which python
          python -V
      - name: brew cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.brew-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ hashFiles('Brewfile') }}
      - name: pip cache
        uses: actions/cache@v1
        if: startsWith(runner.os, 'macOS')
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: install task
        run: |
          brew install pipenv
          sudo easy_install pip
          which pip
          pip -V
          sudo pip install mock --upgrade --ignore-installed six
          sudo pip install pyobjc
      - name: run test
        run: python -m unittest discover --start-directory ./tests/scripts
